# Site settings

baseurl: ""
url: "https://vlagorce.com"

# Build settings
source:      .
destination: ./_site
plugins_dir: ./_plugin
markdown: kramdown
permalink: /:lcl/
author: "Vincent Lagorce"

exclude:
  - "README.md"
  - "LICENSE"
  - "*.iml"
  - "Gemfile"
  - "Gemfile.lock"

keep_files:
# - "CNAME"
#  - ".git"
#  - ".gitignore"

languages:
   - lang: 'fr'
     path: '/'
     language: 'Français'
   - lang: 'de'
     path: '/de/'
     language: 'Deutsch'
   - lang: 'it'
     path: '/it/'
     language: 'Italiano'
   - lang: 'en'
     path: '/en/'
     language: 'English'

#
# plugin configuration
#
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

collections:
  pages:
    output: true

#using Jekyll in safe mode to mimic GitHub Pages
whitelist:
  - jekyll-redirect-from

# Google analytics
ga_tracking_id: "UA-101350494-1"

#
# other configuration
#

git-hub:
  username: vlagorce

twitter:
  username: vlagorce

linkedin:
  username: vlagorce

stack_of:
  username: vlagorce

email: contact@vlagorce.com

social:
  name: Vincent Lagorce
  links:
    - https://github.com/vlagorce
    - https://twitter.com/vlagorce
    - https://stackoverflow.com/story/vlagorce
    - https://linkedin.com/in/vlagorce
